name: Build and deploy to GitHub Pages

on: 
  push:
    branches: 
      - '*'
      - '!main'
  pull_request:
    branches: 
      - '*'
      - '!main'

permissions: write-all

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate
